// app/components/EmptyState.tsx
import { Link } from '@tanstack/react-router'

interface EmptyStateProps {
  title?: string
  message?: string
  icon?: string
  showClearButton?: boolean
}

export function EmptyState({
  title = 'No Pals found',
  message = 'Try adjusting your search filters',
  icon = '🔍',
  showClearButton = true,
}: EmptyStateProps) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-gray-500">
      <span className="text-6xl mb-4">{icon}</span>
      <h3 className="text-xl font-semibold mb-2">{title}</h3>
      <p className="text-sm mb-4">{message}</p>
      {showClearButton && (
        <Link
          to="/"
          search={{}}
          className="px-4 py-2 bg-blue-600 text-white rounded-md text-sm hover:bg-blue-700 transition-colors"
        >
          Clear all filters
        </Link>
      )}
    </div>
  )
}

export function NotFoundState({ message = 'The page you are looking for does not exist.' }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-gray-500">
      <span className="text-6xl mb-4">😕</span>
      <h3 className="text-xl font-semibold mb-2">Page Not Found</h3>
      <p className="text-sm mb-4">{message}</p>
      <Link
        to="/"
        className="px-4 py-2 bg-blue-600 text-white rounded-md text-sm hover:bg-blue-700 transition-colors"
      >
        Go to Home
      </Link>
    </div>
  )
}

export function PalNotFoundState({ palId }: { palId: string }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-gray-500">
      <span className="text-6xl mb-4">🎮</span>
      <h3 className="text-xl font-semibold mb-2">Pal Not Found</h3>
      <p className="text-sm mb-4">
        No Pal with ID "{palId}" exists in the Paldex.
      </p>
      <Link
        to="/"
        className="px-4 py-2 bg-blue-600 text-white rounded-md text-sm hover:bg-blue-700 transition-colors"
      >
        Browse All Pals
      </Link>
    </div>
  )
}

// app/components/EmptyState.vue
<script setup lang="ts">
import { Link } from '@tanstack/vue-router'

withDefaults(defineProps<{
  title?: string
  message?: string
  icon?: string
  showClearButton?: boolean
}>(), {
  title: 'No Pals found',
  message: 'Try adjusting your search filters',
  icon: '🔍',
  showClearButton: true,
})
</script>

<template>
  <div class="flex flex-col items-center justify-center py-16 text-gray-500">
    <span class="text-6xl mb-4">{{ icon }}</span>
    <h3 class="text-xl font-semibold mb-2">{{ title }}</h3>
    <p class="text-sm mb-4">{{ message }}</p>
    <Link
      v-if="showClearButton"
      to="/"
      :search="{}"
      class="px-4 py-2 bg-blue-600 text-white rounded-md text-sm hover:bg-blue-700 transition-colors"
    >
      Clear all filters
    </Link>
  </div>
</template>
